apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-nginx-load-balancer-conf
  labels:
    k8s-app: nginx-ingress-controller
  namespace: kube-system
data:
{{ toYaml .Values.nginx_annotation | indent 3 }}
