apiVersion: "{{ .Values.waf_config.crd_group }}/{{ .Values.waf_config.crd_version }}"
kind: Nginxcert
metadata:
  name: {{ .Values.waf_config.waf_name }}
  labels:
    waf_name: {{ .Values.waf_config.waf_name }}
  namespace: {{ .Values.waf_config.brand }}
spec:
  waf_name: {{ .Values.waf_config.waf_name }}
  block_type: "http"
  http:
    proxy-protocol: false