#!/bin/bash

if [ ! -d /var/log/nginx/ ]; then
	mkdir -p /var/log/nginx/
fi

if [ ! -f "/etc/nginx/nginx.conf" ]; then
	cp /nginx.conf /etc/nginx/nginx.conf
fi

/usr/local/openresty/bin/openresty -c /etc/nginx/nginx.conf