apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-protocol-template
  namespace: kube-system
data:
  nginx_template_configmap: |-
{{ .Values.nginx_ingress_template | indent 3 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-waf-proxy-protocol-template
  namespace: kube-system
data:
  nginx_waf_template: |-
{{ .Values.nginx_waf_template | indent 3 }}
